---
- name: "Creates backend app directory"
  file:
    path: /home/ubuntu/backend-app
    state: directory

- name: Copy backend files
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend-app/

- name: "Check for tar file"
  become: true
  command:
    ls -l /home/ubuntu/backend-app/artifact.tar.gz

- name: "Unarchive backend files"
  unarchive:
    remote_src: true
    src: /home/ubuntu/backend-app/artifact.tar.gz
    dest: /home/ubuntu/backend-app

- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu
    echo 'in /home/ubuntu'
    ls
    cd /home/ubuntu/backend-app
     echo 'in /home/ubuntu/backend-app'
    ls
    npm install

- name: "Executing Node app with PM2"
  shell: |
    cd /home/ubuntu/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
